// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-K7gpav1yN_kg2MmW9DlH_F4jMUkXlk',
    appId: '1:934444276152:web:352aa32bbd86c81775174d',
    messagingSenderId: '934444276152',
    projectId: 'eu-shared-tasks',
    authDomain: 'eu-shared-tasks.firebaseapp.com',
    storageBucket: 'eu-shared-tasks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoboBLlLeXTywPL4KhyQfuiy7NEa2y2DE',
    appId: '1:934444276152:android:9c60b6af36d5b0cf75174d',
    messagingSenderId: '934444276152',
    projectId: 'eu-shared-tasks',
    storageBucket: 'eu-shared-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbAR0hJwd-nyVFXZ6_eOyspJ5m_288Uz4',
    appId: '1:934444276152:ios:3792e53b57eabda275174d',
    messagingSenderId: '934444276152',
    projectId: 'eu-shared-tasks',
    storageBucket: 'eu-shared-tasks.appspot.com',
    iosBundleId: 'com.example.eu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbAR0hJwd-nyVFXZ6_eOyspJ5m_288Uz4',
    appId: '1:934444276152:ios:c3589d6c9f78b56f75174d',
    messagingSenderId: '934444276152',
    projectId: 'eu-shared-tasks',
    storageBucket: 'eu-shared-tasks.appspot.com',
    iosBundleId: 'com.example.eu.RunnerTests',
  );
}
